#!/bin/bash

FREE=`df -k --output=avail /home| tail -n1`
echo $FREE

if [[ $FREE -gt 2097152 ]]; then 
     # 10G = 10*1024*1024 = 10485760
     # 2G  = 2*1024*1024 = 2097152
     fsarchiver savefs -A -z5 /home/pi/sda2-root.fsa /dev/sda2
fi

