#!/bin/bash

upSeconds=`cat /proc/uptime`
upSeconds=${upSeconds%%.*}

#43200 is 12 hours
#10800 is 3 hours
if [ "${upSeconds}" -le 10800 ]; then
   exit 0
fi
   exit 0

DIRECTORY=/home/mg44_fsa
if [ ! -d "$DIRECTORY" ]; then
   echo $DIRECTORY "doesn't exist. Exiting gracefully."
   echo "/home/mg44_fsa not mounted" | mail -s "mg44 fsa failed" root
   exit 0
fi

FREE=`df -k --output=avail /home| tail -n1`
echo $FREE

if [[ $FREE -gt 41943040 ]]; then 
   new_dir=`date +%F`
	mkdir "$new_dir"
	cd "$new_dir"
	tar zcf etc.tar.gz /etc
   # 10G = 10*1024*1024 = 10485760
   # 2G  = 2*1024*1024 = 2097152
	fsarchiver savefs -j4 -z5 -A -s 600 sda10-root.fsa /dev/sda10
	md5sum * | tee MD5SUMS
	df -h >> README
#### Warning
   find /home/mg44_fsa -mtime +60 -exec rm -r '{}' \;
fi
exit 0
