#!/bin/bash

#43200 is 12 hours
upSeconds=`cat /proc/uptime`
upSeconds=${upSeconds%%.*}

if [ "${upSeconds}" -le 43200 ]; then
   exit 0
fi

LANG=en_US
LC_TYPE=en_US

ufw allow to any port 443
certbot renew
ufw delete allow to any port 443

exit 0
