#!/bin/bash

TEMP_DIR=$(mktemp -d /tmp/chromium.XXXXXXX) ; /usr/bin/chromium-browser --user-data-dir=$TEMP_DIR --load-extension=/home/username/Downloads/crx/cjpalhdlnbpafiamejdnhcphjbkeiagm --disable-sync  ; rm -fr $TEMP_DIR
